// Product catalog — shared across all pages
const PRODUCTS = [
  { id: "p5", name: "Grid Traffic", category: "posters", price: 99, image: "posters/poster-01.jpg", desc: "Painterly aerial view of racing cars weaving through a stylized interchange.", rot: -3 },
  { id: "p6", name: "Lived In Books", category: "posters", price: 99, image: "posters/poster-02.jpg", desc: "Bold typographic print laid over vintage dictionary pages.", rot: 2 },
  { id: "p7", name: "Cosmopolitan", category: "posters", price: 99, image: "posters/poster-03.jpg", desc: "Hand-illustrated cocktail recipe print with soft pink tones.", rot: -1 },
  { id: "p8", name: "What If It Works Out", category: "posters", price: 99, image: "posters/poster-04.jpg", desc: "Bold newsprint-style typographic statement piece, black and red.", rot: 4 },
  { id: "p9", name: "POSTER NAME 1", category: "posters", price: 99, image: "posters/poster-05.jpg", desc: "Short description here.", rot: -3 },
  { id: "p10", name: "POSTER NAME 2", category: "posters", price: 99, image: "posters/poster-06.jpg", desc: "Short description here.", rot: -2 },
  { id: "p11", name: "POSTER NAME 3", category: "posters", price: 99, image: "posters/poster-07.jpg", desc: "Short description here.", rot: -1 },
  { id: "p12", name: "POSTER NAME 4", category: "posters", price: 349, image: "posters/poster-08.jpg", desc: "Short description here.", rot: 1 },
  { id: "p13", name: "POSTER NAME 5", category: "posters", price: 349, image: "posters/poster-09.jpg", desc: "Short description here.", rot: 2 },
  { id: "p14", name: "POSTER NAME 6", category: "posters", price: 349, image: "posters/poster-10.jpg", desc: "Short description here.", rot: 3 },
  { id: "p15", name: "POSTER NAME 7", category: "posters", price: 349, image: "posters/poster-11.jpg", desc: "Short description here.", rot: 4 },
  { id: "p16", name: "POSTER NAME 8", category: "posters", price: 349, image: "posters/poster-12.jpg", desc: "Short description here.", rot: -4 },
  { id: "p17", name: "POSTER NAME 9", category: "posters", price: 349, image: "posters/poster-13.jpg", desc: "Short description here.", rot: -3 },
  { id: "p18", name: "POSTER NAME 10", category: "posters", price: 349, image: "posters/poster-14.jpg", desc: "Short description here.", rot: -2 },
  { id: "p19", name: "POSTER NAME 11", category: "posters", price: 349, image: "posters/poster-15.jpg", desc: "Short description here.", rot: -1 },
  { id: "p20", name: "POSTER NAME 12", category: "posters", price: 349, image: "posters/poster-16.jpg", desc: "Short description here.", rot: 1 },
  { id: "p21", name: "POSTER NAME 13", category: "posters", price: 349, image: "posters/poster-17.jpg", desc: "Short description here.", rot: 2 },
  { id: "p22", name: "POSTER NAME 14", category: "posters", price: 349, image: "posters/poster-18.jpg", desc: "Short description here.", rot: 3 },
  { id: "p23", name: "POSTER NAME 15", category: "posters", price: 349, image: "posters/poster-19.jpg", desc: "Short description here.", rot: 4 },
  { id: "p24", name: "POSTER NAME 16", category: "posters", price: 349, image: "posters/poster-20.jpg", desc: "Short description here.", rot: -4 },
  { id: "p25", name: "POSTER NAME 17", category: "posters", price: 349, image: "posters/poster-21.jpg", desc: "Short description here.", rot: -3 },
  { id: "p26", name: "POSTER NAME 18", category: "posters", price: 349, image: "posters/poster-22.jpg", desc: "Short description here.", rot: -2 },
  { id: "p27", name: "POSTER NAME 19", category: "posters", price: 349, image: "posters/poster-23.jpg", desc: "Short description here.", rot: -1 },
  { id: "p28", name: "POSTER NAME 20", category: "posters", price: 349, image: "posters/poster-24.jpg", desc: "Short description here.", rot: 1 },
  { id: "p29", name: "POSTER NAME 21", category: "posters", price: 349, image: "posters/poster-25.jpg", desc: "Short description here.", rot: 2 },
  { id: "p30", name: "POSTER NAME 22", category: "posters", price: 349, image: "posters/poster-26.jpg", desc: "Short description here.", rot: 3 },
  { id: "p31", name: "POSTER NAME 23", category: "posters", price: 349, image: "posters/poster-27.jpg", desc: "Short description here.", rot: 4 },
  { id: "p32", name: "POSTER NAME 24", category: "posters", price: 349, image: "posters/poster-28.jpg", desc: "Short description here.", rot: -4 },
  { id: "p33", name: "POSTER NAME 25", category: "posters", price: 349, image: "posters/poster-29.jpg", desc: "Short description here.", rot: -3 },
  { id: "p34", name: "POSTER NAME 26", category: "posters", price: 349, image: "posters/poster-30.jpg", desc: "Short description here.", rot: -2 },
  { id: "p35", name: "POSTER NAME 27", category: "posters", price: 349, image: "posters/poster-31.jpg", desc: "Short description here.", rot: -1 },
  { id: "p36", name: "POSTER NAME 28", category: "posters", price: 349, image: "posters/poster-32.jpg", desc: "Short description here.", rot: 1 },
  { id: "p37", name: "POSTER NAME 29", category: "posters", price: 349, image: "posters/poster-33.jpg", desc: "Short description here.", rot: 2 },
  { id: "p38", name: "POSTER NAME 30", category: "posters", price: 349, image: "posters/poster-34.jpg", desc: "Short description here.", rot: 3 },
  { id: "p39", name: "POSTER NAME 31", category: "posters", price: 349, image: "posters/poster-35.jpg", desc: "Short description here.", rot: 4 },
  { id: "p40", name: "POSTER NAME 32", category: "posters", price: 349, image: "posters/poster-36.jpg", desc: "Short description here.", rot: -4 },
  { id: "p41", name: "POSTER NAME 33", category: "posters", price: 349, image: "posters/poster-37.jpg", desc: "Short description here.", rot: -3 },
  { id: "p42", name: "POSTER NAME 34", category: "posters", price: 349, image: "posters/poster-38.jpg", desc: "Short description here.", rot: -2 },
  { id: "p43", name: "POSTER NAME 35", category: "posters", price: 349, image: "posters/poster-39.jpg", desc: "Short description here.", rot: -1 },
  { id: "p44", name: "POSTER NAME 36", category: "posters", price: 349, image: "posters/poster-40.jpg", desc: "Short description here.", rot: 1 },
  { id: "p45", name: "POSTER NAME 37", category: "posters", price: 349, image: "posters/poster-41.jpg", desc: "Short description here.", rot: 2 },
  { id: "p46", name: "POSTER NAME 38", category: "posters", price: 349, image: "posters/poster-42.jpg", desc: "Short description here.", rot: 3 },
  { id: "p47", name: "POSTER NAME 39", category: "posters", price: 349, image: "posters/poster-43.jpg", desc: "Short description here.", rot: 4 },
  { id: "p48", name: "POSTER NAME 40", category: "posters", price: 349, image: "posters/poster-44.jpg", desc: "Short description here.", rot: -4 },
  { id: "p49", name: "POSTER NAME 41", category: "posters", price: 349, image: "posters/poster-45.jpg", desc: "Short description here.", rot: -3 },
  { id: "p50", name: "POSTER NAME 42", category: "posters", price: 349, image: "posters/poster-46.jpg", desc: "Short description here.", rot: -2 },
  { id: "p51", name: "POSTER NAME 43", category: "posters", price: 349, image: "posters/poster-47.jpg", desc: "Short description here.", rot: -1 },
  { id: "p52", name: "POSTER NAME 44", category: "posters", price: 349, image: "posters/poster-48.jpg", desc: "Short description here.", rot: 1 },
  { id: "p53", name: "POSTER NAME 45", category: "posters", price: 349, image: "posters/poster-49.jpg", desc: "Short description here.", rot: 2 },
  { id: "p54", name: "POSTER NAME 46", category: "posters", price: 349, image: "posters/poster-50.jpg", desc: "Short description here.", rot: 3 },
  { id: "p55", name: "POSTER NAME 47", category: "posters", price: 349, image: "posters/poster-51.jpg", desc: "Short description here.", rot: 4 },
  { id: "p56", name: "POSTER NAME 48", category: "posters", price: 349, image: "posters/poster-52.jpg", desc: "Short description here.", rot: -4 },
  { id: "p57", name: "POSTER NAME 49", category: "posters", price: 349, image: "posters/poster-53.jpg", desc: "Short description here.", rot: -3 },
  { id: "p58", name: "POSTER NAME 50", category: "posters", price: 349, image: "posters/poster-54.jpg", desc: "Short description here.", rot: -2 },
  { id: "p59", name: "POSTER NAME 51", category: "posters", price: 349, image: "posters/poster-55.jpg", desc: "Short description here.", rot: -1 },
  { id: "p60", name: "POSTER NAME 52", category: "posters", price: 349, image: "posters/poster-56.jpg", desc: "Short description here.", rot: 1 },
  { id: "p61", name: "POSTER NAME 53", category: "posters", price: 349, image: "posters/poster-57.jpg", desc: "Short description here.", rot: 2 },
  { id: "p62", name: "POSTER NAME 54", category: "posters", price: 349, image: "posters/poster-58.jpg", desc: "Short description here.", rot: 3 },
  { id: "p63", name: "POSTER NAME 55", category: "posters", price: 349, image: "posters/poster-59.jpg", desc: "Short description here.", rot: 4 },
  { id: "p64", name: "POSTER NAME 56", category: "posters", price: 349, image: "posters/poster-60.jpg", desc: "Short description here.", rot: -4 },
  { id: "p65", name: "POSTER NAME 57", category: "posters", price: 349, image: "posters/poster-61.jpg", desc: "Short description here.", rot: -3 },
  { id: "p66", name: "POSTER NAME 58", category: "posters", price: 349, image: "posters/poster-62.jpg", desc: "Short description here.", rot: -2 },
  { id: "p67", name: "POSTER NAME 59", category: "posters", price: 349, image: "posters/poster-63.jpg", desc: "Short description here.", rot: -1 },
  { id: "p68", name: "POSTER NAME 60", category: "posters", price: 349, image: "posters/poster-64.jpg", desc: "Short description here.", rot: 1 },
  { id: "p69", name: "POSTER NAME 61", category: "posters", price: 349, image: "posters/poster-65.jpg", desc: "Short description here.", rot: 2 },
  { id: "p70", name: "POSTER NAME 62", category: "posters", price: 349, image: "posters/poster-66.jpg", desc: "Short description here.", rot: 3 },
  { id: "p71", name: "POSTER NAME 63", category: "posters", price: 349, image: "posters/poster-67.jpg", desc: "Short description here.", rot: 4 },
  { id: "p72", name: "POSTER NAME 64", category: "posters", price: 349, image: "posters/poster-68.jpg", desc: "Short description here.", rot: -4 },
  { id: "p73", name: "POSTER NAME 65", category: "posters", price: 349, image: "posters/poster-69.jpg", desc: "Short description here.", rot: -3 },
  { id: "p74", name: "POSTER NAME 66", category: "posters", price: 349, image: "posters/poster-70.jpg", desc: "Short description here.", rot: -2 },
  { id: "p75", name: "POSTER NAME 67", category: "posters", price: 349, image: "posters/poster-71.jpg", desc: "Short description here.", rot: -1 },
  { id: "p76", name: "POSTER NAME 68", category: "posters", price: 349, image: "posters/poster-72.jpg", desc: "Short description here.", rot: 1 },
  { id: "p77", name: "POSTER NAME 69", category: "posters", price: 349, image: "posters/poster-73.jpg", desc: "Short description here.", rot: 2 },
  { id: "p78", name: "POSTER NAME 70", category: "posters", price: 349, image: "posters/poster-74.jpg", desc: "Short description here.", rot: 3 },
  { id: "p79", name: "POSTER NAME 71", category: "posters", price: 349, image: "posters/poster-75.jpg", desc: "Short description here.", rot: 4 },
];

function getProduct(id) {
  return PRODUCTS.find(p => p.id === id);
}
